[package]
name = "hydra"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1"
winit = { version = "0.29", features = ["rwh_05"] }
env_logger = "0.10"
log = "0.4"
wgpu = "0.19.3"
pollster = "0.3"


#Web dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
#log to javascript console
console_error_panic_hook = "0.1.6"
#send all log levels to js console
console_log = "1.0"
#need wgpu webgl fallback
wgpu = { version = "0.19", features = ["webgl"]}
#allows easy rust-js interop
wasm-bindgen = "0.2"
#useful for async code
wasm-bindgen-futures = "0.4.30"
#can access js DOM in rust
web-sys = { version = "0.3", features = [
    "Document",
    "Window",
    "Element",
]}

#cdylib: for c/c++ compatiblity; run in wasm
#rlib: for rust static lib; run in desktop environment
[lib]
crate-type = ["cdylib", "rlib"]